import {createClient,SupabaseClient} from '@supabase/supabase-js';
import {useState,ReactNode} from 'react';
import {toast} from 'sonner';
import {Vehicle,numericFields} from './cost';
let client:SupabaseClient|null=null;
export function validateConfig(url:string,key:string){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw new Error('請使用 HTTPS 的 Supabase Project URL');if(key.startsWith('sb_secret_'))throw new Error('請勿使用 secret 或 service_role 金鑰');if(!key.startsWith('sb_publishable_')){try{const role=JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role;if(role!=='anon')throw Error();}catch{throw new Error('請使用 publishable key 或 anon public key');}}return {url:u.origin,key};}
export function configure(url:string,key:string){const c=validateConfig(url,key);client=createClient(c.url,c.key);return client;}
export function cloud(){if(!client)throw new Error('請先設定雲端連線');return client;}
async function owner(){const {data,error}=await cloud().auth.getUser();if(error||!data.user)throw new Error('登入已過期，請重新登入');return data.user.id;}
async function rows(table:string){const result:any[]=[];for(let from=0;from<10000;from+=500){const {data,error}=await cloud().from(table).select('*').order('created_at',{ascending:false}).order('id').range(from,from+499);if(error)throw new Error('雲端讀取失敗，請確認資料庫初始化與存取設定');result.push(...data);if(data.length<500)return result;}throw new Error('資料超過一萬筆，請縮小資料庫後再載入');}
function validateVehicle(v:Vehicle){if(!/^[0-9a-f-]{36}$/i.test(v.id)||!['draft','confirmed'].includes(v.status))throw new Error('資料格式不正確');for(const k of numericFields){if(v[k]!==null&&(!Number.isFinite(v[k])||v[k]!<0))throw new Error('數字不得小於 0');}for(const k of ['quota','stock'] as const)if(v[k]!==null&&!Number.isInteger(v[k]))throw new Error('配額與庫存請填整數');if(v.status==='confirmed'&&!v.model.trim())throw new Error('請填寫車型');for(const date of [v.validFrom,v.validTo])if(date&&!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('日期格式應為 YYYY-MM-DD');if(v.validFrom&&v.validTo&&v.validTo<v.validFrom)throw new Error('截止日不可早於生效日');}
export async function api(url:string,opts?:RequestInit):Promise<any>{
 await owner();if(url==='/api/data'&&!opts){const [v,s]=await Promise.all([rows('jc_vehicles'),rows('jc_sources')]);return {vehicles:v.map(x=>({...x.body,createdAt:x.created_at})),sources:s};}
 if(url==='/api/data'&&opts?.method==='POST'){const v=JSON.parse(String(opts.body)) as Vehicle;validateVehicle(v);const id=await owner();const {error}=await cloud().from('jc_vehicles').upsert({id:v.id,owner_id:id,source_id:v.sourceId||null,body:v},{onConflict:'id'});if(error)throw new Error('雲端儲存失敗，請確認來源資料及資料庫設定');return {vehicle:v};}
 if(url==='/api/upload'&&opts?.method==='POST'){const file=(opts.body as FormData).get('file');if(!(file instanceof File)||!file.size||file.size>15*1024*1024)throw new Error('單檔上限 15 MB，且不可空白');const ext=file.name.split('.').pop()?.toLowerCase();if(!['pdf','png','jpg','jpeg','webp','xlsx','xls','csv','txt','eml','docx'].includes(ext||''))throw new Error('不支援這個檔案格式');const uid=await owner(),id=crypto.randomUUID(),key=`${uid}/${id}`;const {error:uploadError}=await cloud().storage.from('jc-files').upload(key,file,{contentType:file.type||'application/octet-stream',upsert:false});if(uploadError)throw new Error('檔案上傳失敗，請確認檔案儲存設定');const {error}=await cloud().from('jc_sources').insert({id,owner_id:uid,name:file.name.slice(0,240),object_key:key,type:file.type||ext});if(error){await cloud().storage.from('jc-files').remove([key]);throw new Error('來源資料保存失敗，請重試');}return {id,name:file.name};}
 throw new Error('不支援的操作');
}
export async function sourceDownload(id:string){await owner();const {data,error}=await cloud().from('jc_sources').select('name,object_key').eq('id',id).single();if(error||!data)throw new Error('找不到來源檔案');const download=await cloud().storage.from('jc-files').download(data.object_key);if(download.error||!download.data)throw new Error('無法下載檔案，請重新登入或稍後重試');return {name:data.name,blob:download.data};}
export function SourceLink({id,children,className}:{id:string;children:ReactNode;className?:string}){const [busy,setBusy]=useState(false);return <button type="button" className={`source-download ${className||''}`} disabled={busy} onClick={async()=>{setBusy(true);try{const f=await sourceDownload(id);const url=URL.createObjectURL(f.blob),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>{busy?'下載中…':children}</button>;}
