import {useEffect,useState} from 'react';
import type {Session,SupabaseClient} from '@supabase/supabase-js';
import Workspace from './workspace';import {configure,validateConfig} from '@/lib/cloud';
const envConfig={url:import.meta.env.VITE_SUPABASE_URL||'',key:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||''};
export default function App(){const [config,setConfig]=useState(()=>{try{return JSON.parse(localStorage.getItem('jc-cloud-config')||'null')||envConfig;}catch{return envConfig;}}),[url,setUrl]=useState(config.url),[key,setKey]=useState(config.key),[client,setClient]=useState<SupabaseClient|null>(null),[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setReady(false);setSession(null);if(!config.url||!config.key){setReady(true);return;}try{const c=configure(config.url,config.key);setClient(c);void c.auth.getSession().then(({data,error})=>{if(error)setError('無法讀取登入狀態，請重新登入');setSession(data.session);setReady(true);});const {data}=c.auth.onAuthStateChange((_event,session)=>{setSession(session);setReady(true);});return ()=>data.subscription.unsubscribe();}catch(e){setError((e as Error).message);setClient(null);setReady(true);}},[config]);
 function applyConfig(){try{const c=validateConfig(url.trim(),key.trim());localStorage.setItem('jc-cloud-config',JSON.stringify(c));setError('');setConfig(c);}catch(e){setError((e as Error).message);}}
 async function login(){if(!client)return;setBusy(true);setError('');try{const {error}=await client.auth.signInWithPassword({email:email.trim(),password});if(error)throw new Error('登入失敗，請確認信箱與密碼；首次使用須先建立雲端帳號。');setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!ready)return <main className="login-wrap"><section className="panel login-panel"><h1>JC 車型成本工作台</h1><p role="status">正在確認登入狀態…</p></section></main>;
 if(session&&client)return <><div className="account-strip"><span>{session.user.email} · 雲端帳號</span><button onClick={async()=>{const {error}=await client.auth.signOut();if(error){setError('登出失敗，請重試');return;}setSession(null);}}>登出</button></div><Workspace key={session.user.id}/></>;
 return <main className="login-wrap"><section className="panel login-panel"><div className="eyebrow">GITHUB PAGES · CLOUD EDITION</div><h1>JC 車型成本工作台</h1><p>登入同一個帳號，在手機與電腦查看相同車型資料。</p>{error&&<div className="notice error" role="alert">{error}</div>}{client?<form onSubmit={e=>{e.preventDefault();void login();}}><label>信箱<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>密碼<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={busy}>{busy?'登入中…':'登入私人資料庫'}</button><small>請使用雲端後台已建立的帳號。此登入不會授權讀取 Gmail。</small><button type="button" className="text-button" onClick={()=>{setClient(null);setConfig({url:'',key:''});localStorage.removeItem('jc-cloud-config');}}>調整雲端設定</button></form>:<form onSubmit={e=>{e.preventDefault();applyConfig();}}><h2>首次連線設定</h2><p>先依部署說明建立 Supabase 專案，再填入公開連線資訊。</p><label>Project URL<input type="url" value={url} placeholder="https://你的專案.supabase.co" onChange={e=>setUrl(e.target.value)} required/></label><label>Publishable／anon public key<textarea value={key} onChange={e=>setKey(e.target.value)} placeholder="僅填公開金鑰" required/></label><button className="primary">保存連線設定</button><small>這裡只保存公開連線設定；請勿填 service_role 或 secret 金鑰。成本與檔案保存於私人雲端後台。</small></form>}</section></main>;
}
