import {useEffect,useState} from 'react';
import {Vehicle} from '../lib/cost';
import {modelKey} from '../lib/packages';
import {SourceLink} from '../lib/cloud';
const money=(v:number|null)=>v===null?'未提供':`$${v.toLocaleString('zh-TW')}`;
export default function PackagePicker({packages,model,onPick}:{packages:Vehicle[];model?:string;onPick?:(v:Vehicle|undefined,basis:'bundlePrice'|'dealerTotal')=>void}){
 const [basis,setBasis]=useState<'bundlePrice'|'dealerTotal'>('dealerTotal');
 const [car,setCar]=useState(modelKey(model||'')),[id,setId]=useState('');
 useEffect(()=>{setCar(modelKey(model||''));setId('');},[model]);
 const models=[...new Set(packages.map(p=>modelKey(p.model)))].sort();
 const options=packages.filter(p=>modelKey(p.model)===car);const chosen=options.find(p=>p.id===id);const info=chosen?.packageInfo;
 return <section className="panel package-panel"><h2>對應配件套裝</h2><p>選車型，再選套裝與適用版本。不同工作表的方案分開顯示，請核對日期。</p><div className="package-selects"><label>車型<select value={car} onChange={e=>{setCar(e.target.value);setId('');onPick?.(undefined,basis);}} disabled={!!model}><option value="">請選車型</option>{models.map(m=><option key={m} value={m}>{m}</option>)}{car&&!models.includes(car)&&<option value={car}>{car}</option>}</select></label><label>套裝／適用版本<select value={id} onChange={e=>{setId(e.target.value);onPick?.(options.find(p=>p.id===e.target.value),basis);}}><option value="">請選套裝</option>{options.map(p=><option key={p.id} value={p.id}>{p.packageInfo?.code} · {p.trim||'依原表適用'} · {p.packageInfo?.sheet}</option>)}</select></label></div>{!options.length&&<p>尚無此車型的已確認套裝，請上傳套裝 Excel 並核對確認。</p>}{info&&chosen&&<><div className="price-toggle" role="group" aria-label="選擇套裝計價方式">{(['bundlePrice','dealerTotal'] as const).map((key,i)=><button key={key} className={basis===key?'primary':'secondary'} aria-pressed={basis===key} onClick={()=>{setBasis(key);onPick?.(chosen,key);}}>{['套裝價格','業代價格'][i]}</button>)}</div><p className="notice">目前帶入：{basis==='bundlePrice'?'套裝價格':'業代價格'} · {money(info[basis])}</p><h3>{chosen.model} · {info.code}</h3><p style={{whiteSpace:'pre-wrap'}}>適用版本：{chosen.trim||'請核對原表'}</p><div className="cost-cards"><div><span>業代價合計</span><strong>{money(info.dealerTotal)}</strong></div><div><span>表列套裝價</span><strong>{money(info.bundlePrice)}</strong></div><div><span>統一報價</span><strong>{money(info.quote)}</strong></div></div><div className="package-table"><table><thead><tr><th>配件編號</th><th>品名</th><th>業代價</th></tr></thead><tbody>{info.items.map((item,i)=><tr key={i}><td>{item.code}</td><td>{item.name}</td><td>{money(item.price)}</td></tr>)}</tbody></table></div><p>來源：{info.sheet} {chosen.sourceId&&<SourceLink id={chosen.sourceId}>下載原檔</SourceLink>}</p><p>上述為配件金額，未包含空車成本。</p></>}</section>;
}
