'use client';
import {useEffect,useRef,useState} from 'react';
import {Car,Search,Upload,FileText,Mail,Plus,Check,ShieldCheck,Database,Wallet,CircleHelp,Download,RefreshCw,Layers,Package,CalendarDays,Pencil,LoaderCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import {blank,Vehicle,labels,numericFields,calculate,effective,expired,parseText} from '@/lib/cost';
import NumericInput from './NumericInput';
import {monthlyConditions,companyTerms} from '@/lib/monthly';
import PackagePicker from './PackagePicker';
import {modelKey} from '@/lib/packages';
import {extract} from '@/lib/extract';
import {api,SourceLink,sourceDownload} from '@/lib/cloud';
const fmt=(n:number|null)=>n===null?'待補資料':new Intl.NumberFormat('zh-TW',{maximumFractionDigits:0}).format(n);
const defaultScenario={sale:0,extras:0,subsidy:0,trade:0,debt:0,down:0,rate:0,months:60,fees:0,dealerCost:0,referencePrice:0,rebate:0,commission:0,rebatePercent:0,commissionPercent:0};
const scenarioLabels:Record<string,string>={sale:'成交車價（折扣後）',extras:'另收配件／服務費',subsidy:'核准舊換新補助',trade:'舊車收購折抵',debt:'舊車待清償貸款',down:'預計頭期款',rate:'車貸年利率（%）',months:'貸款期數（月）',fees:'客戶額外現金費用',dealerCost:'業務其他成本',referencePrice:'車價基準／牌價（百分比使用）',rebate:'原廠額外獎金／折讓（元）',rebatePercent:'原廠額外獎金（%）',commission:'車貸佣金（元）',commissionPercent:'車貸佣金（貸款本金 %）'};
export default function Workspace(){
 const [tab,setTab]=useState('query'),[vehicles,setVehicles]=useState<Vehicle[]>([]),[sources,setSources]=useState<any[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[mode,setMode]=useState('bare'),[scenario,setScenario]=useState(defaultScenario),[editor,setEditor]=useState<Vehicle|null>(null),[saving,setSaving]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[raw,setRaw]=useState(''),[activeSource,setActiveSource]=useState(''),[filter,setFilter]=useState('all');
 const [priceBasis,setPriceBasis]=useState<'bundlePrice'|'dealerTotal'>('dealerTotal');
 const [conditionId,setConditionId]=useState(''),[conditionYear,setConditionYear]=useState<'26'|'27'>('26'),[qualified,setQualified]=useState(true),[installment,setInstallment]=useState(false),[wholesale,setWholesale]=useState(false),[dealDate,setDealDate]=useState(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}));
 const [pickedPackage,setPickedPackage]=useState<Vehicle|undefined>();
 const uploadInput=useRef<HTMLInputElement>(null);const stateRef=useRef({vehicles,selected});stateRef.current={vehicles,selected};
 async function load(){setLoading(true);try{const d=await api('/api/data');setVehicles(d.vehicles);setSources(d.sources);setLoadError('');}catch(e){setLoadError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:'search_vehicle_costs',description:'查詢已確認車型成本與配車資料，並切換工作台到查詢頁。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:120}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const q=(input as any)?.query;if(typeof q!=='string'||q.length>120)throw new Error('query 必須是 120 字內的文字');setSearch(q);setTab('query');return {records:stateRef.current.vehicles.filter(v=>v.status==='confirmed'&&`${v.model} ${v.trim} ${v.year}`.toLowerCase().includes(q.toLowerCase()))};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[]);
 const packages=vehicles.filter(v=>v.kind==='accessory-package'&&v.status==='confirmed');const confirmed=vehicles.filter(v=>!v.kind&&v.status==='confirmed');const drafts=vehicles.filter(v=>v.status==='draft');const matches=confirmed.filter(v=>`${v.model} ${v.trim} ${v.year} ${v.color}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||effective(v)));
 const v=confirmed.find(x=>x.id===selected)||matches[0];const activePackage=pickedPackage&&v&&modelKey(pickedPackage.model)===modelKey(v.model)?pickedPackage:undefined;const withPackage=v&&activePackage?{...v,package:v.bare!==null&&activePackage.packageInfo?.[priceBasis]!=null?v.bare+activePackage.packageInfo[priceBasis]!:null}:v;const monthlyCondition=monthlyConditions.find(x=>x.id===conditionId);const terms=monthlyCondition?companyTerms(monthlyCondition,conditionYear,qualified,installment,wholesale,dealDate):undefined;const c=withPackage?calculate(withPackage,mode,{...scenario,companyRate:terms?.rate,financeCost:terms?.difference,promoLimit:terms?.limit,promoMonths:terms?.months}):null;
 const vehicleId=v?.id;useEffect(()=>{setScenario({...defaultScenario,rebate:v?.rebate??0,commission:v?.commission??0,rebatePercent:v?.rebatePercent??0,commissionPercent:v?.commissionPercent??0,referencePrice:v?.referencePrice??0});setConditionId('');setPickedPackage(undefined);},[vehicleId,v?.rebate,v?.commission,v?.rebatePercent,v?.commissionPercent,v?.referencePrice]);
 async function save(entry:Vehicle,status:'draft'|'confirmed'){setSaving(true);try{await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...entry,status})});await load();setEditor(null);toast.success(status==='confirmed'?'已確認並加入車型查詢':'草稿已保存');if(status==='confirmed'){if(entry.kind)setTab('packages');else {setSelected(entry.id);setSearch('');}}}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
 async function intake(files:FileList|File[]){if(busy)return;setBusy(true);setTab('intake');let saved=0;try{for(const file of Array.from(files)){setProgress(`上傳 ${file.name}`);let source:any;try{const form=new FormData();form.append('file',file);source=await api('/api/upload',{method:'POST',body:form});setActiveSource(source.id);const result=await extract(file,setProgress);setRaw(result.text);for(const [index,record] of result.records.entries()){setProgress(`保存 ${file.name}：${index+1}／${result.records.length} 筆`);await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...record,sourceId:source.id})});saved++;}}catch(e){toast.error(`${file.name}：${(e as Error).message}`);if(source){setActiveSource(source.id);setRaw('');const draft={...blank(),sourceId:source.id,note:'文字判讀未完成，原檔已保存。請對照檔案補填。'};try{await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});saved++;}catch{toast.error('草稿儲存失敗，原檔可至來源資料下載。');}}}}await load();if(saved)toast.success(`已建立 ${saved} 筆待確認資料`);}finally{setBusy(false);setProgress('');if(uploadInput.current)uploadInput.current.value='';}}
 async function reparseSource(source:any){if(busy)return;setBusy(true);setTab('intake');let count=0;try{setProgress('讀取已上傳 Excel…');const original=await sourceDownload(source.id);const result=await extract(new File([original.blob],original.name),setProgress);setRaw(result.text);for(const record of result.records){const previous=vehicles.find(x=>x.sourceId===source.id&&x.packageInfo&&x.packageInfo.code===record.packageInfo?.code&&x.packageInfo.sheet===record.packageInfo?.sheet);await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...record,id:previous?.id??record.id,sourceId:source.id,status:'draft'})});count++;setProgress(`建立 Excel 草稿 ${count}／${result.records.length}`);}toast.success(`重新解析 ${count} 筆，請核對並確認套裝`);}catch(e){toast.error((e as Error).message);}finally{await load();setBusy(false);setProgress('');}}
 async function textIntake(){if(!raw.trim())return toast.error('請先貼上郵件或書面文字。');setBusy(true);try{const f=new File([raw],`文字資料-${new Date().toISOString().slice(0,10)}.txt`,{type:'text/plain'});const fd=new FormData();fd.append('file',f);const src=await api('/api/upload',{method:'POST',body:fd});setActiveSource(src.id);for(const record of parseText(raw)){await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...record,sourceId:src.id})});}await load();toast.success('文字已判讀，請核對草稿。');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function downloadTemplate(){const csv='\uFEFF車型,等級,年式,空車成本,套裝總成本,原廠獎金,車貸佣金,配車額度,庫存,車色,生效日,截止日,備註\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='車型成本匯入範本.csv';a.click();URL.revokeObjectURL(url);}
 async function confirmPackages(){const entries=drafts.filter(x=>x.kind==='accessory-package'&&x.packageInfo?.items.length);if(!entries.length)return;setSaving(true);let count=0;try{for(const x of entries){await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...x,status:'confirmed'})});count++;}toast.success(`已加入 ${count} 筆配件套裝`);setTab('packages');}catch(e){toast.error(`已加入 ${count} 筆，其餘可重試：${(e as Error).message}`);}finally{await load();setSaving(false);}}
 function choose(x:Vehicle){setPickedPackage(undefined);setSelected(x.id);setScenario(defaultScenario);}
 const sourceName=(id:string)=>sources.find(s=>s.id===id)?.name||'手動建立';
 return <main className="shell"><Toaster richColors position="top-center"/><header className="topbar"><a href={import.meta.env.BASE_URL} className="brand"><span className="brand-icon"><Car size={22}/></span><span>JC <b>車額戰情室</b><small>v1.3.0</small></span></a><span className="private"><ShieldCheck size={16}/>私人工作台</span></header>
 <div className="page-head"><div><div className="eyebrow">車價・成本・配車・試算</div><h1>每一筆成本，都有依據。</h1><p>查車型、核對條件，同時掌握成交毛利與購車支出。</p></div><button className="primary" onClick={()=>{setTab('intake');uploadInput.current?.click();}} disabled={busy}><Upload size={18}/>上傳資料</button></div>
 <input ref={uploadInput} type="file" multiple hidden accept=".pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xls,.csv,.txt,.eml,.docx" onChange={e=>{if(e.target.files)void intake(e.target.files);}}/>
 <div className="metrics"><div><Database/><span>已確認車型條件<strong>{confirmed.length}<small>筆</small></strong></span></div><div><FileText/><span>待核對資料<strong>{drafts.length}<small>筆</small></strong></span></div><div><Package/><span>原始資料<strong>{sources.length}<small>份</small></strong></span></div><div className="mail-metric"><Mail/><span>Gmail 連結<strong className="status-text">尚未連接</strong></span></div></div>
 {loadError&&<div className="notice error" role="alert">{loadError}<button onClick={()=>void load()}>重新載入</button></div>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs"><TabsTrigger value="query"><Search/>車型查詢／試算</TabsTrigger><TabsTrigger value="intake"><Upload/>上傳與核對 {drafts.length>0&&<span className="count">{drafts.length}</span>}</TabsTrigger><TabsTrigger value="packages"><Package/>配件套裝</TabsTrigger><TabsTrigger value="sources"><Layers/>來源資料</TabsTrigger></TabsList>
 <TabsContent value="query"><div className="query-grid"><section className="panel vehicle-list"><div className="panel-title"><h2>車型資料庫</h2><button className="icon-button" aria-label="新增車型" onClick={()=>setEditor(blank())}><Plus size={19}/></button></div><label className="search-box"><Search size={18}/><input value={search} onChange={e=>{setSearch(e.target.value);setSelected('');}} placeholder="搜尋車型、等級、年式、車色" aria-label="搜尋車型"/></label><Select value={filter} onValueChange={setFilter}><SelectTrigger className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">所有已確認條件</SelectItem><SelectItem value="valid">生效中條件</SelectItem></SelectContent></Select><div className="list-count">{loading?'正在載入…':`${matches.length} 筆條件 · 每個版本獨立保存`}</div>
 {!matches.length?<div className="empty"><Car size={38}/><h3>{search?'沒有符合的車型':'先建立你的第一筆車型'}</h3><p>上傳成本表、庫存郵件或書面照片，確認後就能快速查詢。</p><button className="secondary" onClick={()=>setTab('intake')}>匯入車型資料</button><button className="text-button" onClick={()=>setEditor(blank())}>手動新增</button></div>:<div className="vehicle-items">{matches.map(x=><button className={`vehicle-item ${v?.id===x.id?'active':''}`} key={x.id} onClick={()=>choose(x)}><div><strong>{x.model}</strong><span className={`badge ${effective(x)?'blue':'amber'}`}>{expired(x)?'已過期':!effective(x)?'未生效':'已確認'}</span></div><p>{[x.year,x.trim,x.color].filter(Boolean).join(' · ')||'版本尚未填寫'}</p><div className="vehicle-bottom"><span>空車成本</span><b>{x.bare===null?'待補資料':`$${fmt(x.bare)}`}</b></div></button>)}</div>}</section>
 <section className="detail">{v&&c?<><div className="detail-head"><div><div className="eyebrow">車型條件</div><h2>{v.model}</h2><p>{[v.year,v.trim,v.color].filter(Boolean).join(' · ')||'請補填等級與年式以便比對'}</p></div><button className="secondary" onClick={()=>setEditor({...v})}><Pencil size={16}/>編輯條件</button></div>
 {!effective(v)&&<div className="notice">本筆條件{expired(v)?'已過期':'尚未生效'}，以下僅供歷史／未來方案試算。</div>}
 <div className="cost-cards"><div><span>空車成本</span><strong>{v.bare===null?'待補資料':`$${fmt(v.bare)}`}</strong></div><div><span>套裝總成本</span><strong>{withPackage!.package===null?'待補資料':`$${fmt(withPackage!.package)}`}</strong></div><div><span>配車額度／庫存</span><strong>{fmt(v.quota)}<small>／</small>{fmt(v.stock)}</strong></div></div>
 <div className="source-line"><FileText size={15}/>{sourceName(v.sourceId)}{v.sourceId&&<SourceLink id={v.sourceId}>下載原檔</SourceLink>}<span><CalendarDays size={14}/>{v.validFrom||'未填生效日'} ～ {v.validTo||'未填截止日'}</span></div>{v.note&&<p className="conditions">{v.note}</p>}
 <PackagePicker key={v.id} packages={packages} model={v.model} onPick={(p,basis)=>{setPickedPackage(p);setPriceBasis(basis);if(p)setMode('package');}}/>{activePackage&&<div className="notice">套裝試算成本＝空車成本＋{priceBasis==='bundlePrice'?'套裝價格':'業代價格'}；任一未提供時不計算成本。</div>}
 <section className="panel company-panel"><h2>月通報公司條件</h2><p>依你提供的 2026/10/1～10/31 通報；請選正確車型、動力及年式。</p><div className="scenario-fields"><label>月通報方案<select value={conditionId} onChange={e=>{setConditionId(e.target.value);setInstallment(false);}}><option value="">不套用月通報</option>{monthlyConditions.map(x=><option key={x.id} value={x.id}>{x.model}</option>)}</select></label><label>通報年式<select value={conditionYear} onChange={e=>setConditionYear(e.target.value as '26'|'27')}><option value="26">26/26 年式</option><option value="27">27/26 年式</option></select></label><label>領照／適用日期<input type="date" value={dealDate} onChange={e=>setDealDate(e.target.value)}/></label></div><div className="company-checks"><label><input type="checkbox" checked={qualified} onChange={e=>setQualified(e.target.checked)}/>含乙式車體險（含）以上／特採套裝</label><label><input type="checkbox" checked={wholesale} onChange={e=>setWholesale(e.target.checked)}/>批售販賣（不適用支援）</label><label><input type="checkbox" checked={installment} disabled={!monthlyCondition?.limit} onChange={e=>setInstallment(e.target.checked)}/>使用通報零利率分期（扣除差價）</label></div>{monthlyCondition&&terms&&<><p className="notice">現金支援：{terms.rate}% · 分期差價：${fmt(terms.difference)}{installment&&terms.limit>0?` · 零利率上限 $${fmt(terms.limit)}／${terms.months} 期`:''}</p>{(conditionYear==='26'?monthlyCondition.cash26:monthlyCondition.cash27)===null&&<p>該年式未列現金支援，按 0 計算。</p>}{!terms.valid&&<p className="negative">此日期不在通報期間，本次不帶入支援及分期優惠。</p>}{terms.rate>0&&scenario.referencePrice===0&&<p className="negative">請填「車價基準／牌價」，才能計算百分比金額。</p>}<p>支援金額＝車價基準 × 適用百分比；無息差價列為業務成本，原廠額外獎金請勿重複填入相同支援。無乙式險／特採套裝扣 0.5 個百分點。貸款超出優惠上限的部分使用下方利率及期數。</p></>}</section><div className="panel calculator"><div className="panel-title"><h2><Wallet size={19}/>成交試算</h2><span>金額單位 NT$</span></div><div className="calc-layout"><div><div className="mode-row"><label>使用成本方案</label><Select value={mode} onValueChange={setMode}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="bare">空車</SelectItem><SelectItem value="package">套裝</SelectItem></SelectContent></Select></div><div className="scenario-fields">{Object.entries(scenarioLabels).map(([k,label])=><label key={k}>{label}<NumericInput decimal={['rate','rebatePercent','commissionPercent'].includes(k)} min={k==='months'?1:0} max={['rate','rebatePercent','commissionPercent'].includes(k)?100:k==='months'?120:1e9} value={(scenario as any)[k]} onValue={n=>setScenario(prev=>({...prev,[k]:k==='months'?Math.max(1,Math.round(n)):n}))}/></label>)}</div>{(scenario.rebatePercent>0||!!terms?.rate)&&!scenario.referencePrice&&<p className="negative">百分比尚缺車價基準／牌價；目前支援金額按 0 計算。</p>}<p className="field-note">空白試算加項視為 0；百分比獎金依車價基準，佣金比例依貸款本金。套裝欄位使用「總成本」；另收配件須在其他成本納入實際成本。舊換新補助填已核准金額，先扣抵車價再算貸款。</p></div>
 <div className="result"><span className="eyebrow">業務端</span><h3>預估成交毛利</h3><strong className={`result-number ${c.profit!==null&&c.profit<0?'negative':''}`}>{scenario.sale===0?'請輸入成交車價':c.profit===null?'待補成本條件':`$${fmt(c.profit)}`}</strong><p>{scenario.sale===0?'填寫折扣後成交車價，再查看毛利與客戶支出。':c.profit===null?'請填所選方案的空車／套裝成本；可按上方「編輯條件」補填。':'成交車價＋另收費＋額外獎金＋佣金＋公司支援－方案成本－其他成本－無息差價'}</p><dl><div><dt>本次方案成本</dt><dd>{c.cost==null?'待補資料':`$${fmt(c.cost)}`}</dd></div><div><dt>額外獎金／折讓</dt><dd>${fmt(c.rebate)}</dd></div><div><dt>車貸佣金</dt><dd>${fmt(c.commission)}</dd></div><div><dt>月通報公司支援</dt><dd>${fmt(c.companySupport)}</dd></div><div><dt>零利率差價成本</dt><dd>${fmt(c.financeCost)}</dd></div></dl><div className="result-rule"/><span className="eyebrow">客戶端</span><h3>預估每月還款</h3>{c.promoPrincipal>0&&<p>零利率 ${fmt(c.promoPrincipal)}／{c.promoMonths} 期，月付 ${fmt(c.promoMonthly)}；一般分期 {c.months} 期，月付 ${fmt(c.regularMonthly)}。優惠期數結束後停止該部分月付。</p>}<strong className="monthly">${fmt(c.monthly)}<small>／月</small></strong><dl><div><dt>折抵後應付車款</dt><dd>${fmt(c.net)}</dd></div><div><dt>實付頭期款</dt><dd>${fmt(c.cash)}</dd></div><div><dt>貸款本金</dt><dd>${fmt(c.principal)}</dd></div><div><dt>總利息</dt><dd>${fmt(c.interest)}</dd></div><div><dt>現金費用</dt><dd>${fmt(scenario.fees)}</dd></div><div className="total"><dt>含利息總支出</dt><dd>${fmt(c.total)}</dd></div>{c.refund>0&&<div><dt>超額折抵待退回</dt><dd>${fmt(c.refund)}</dd></div>}</dl><p>本息平均攤還，費用以現金另付；月付顯示四捨五入，銀行實際契約與補助核定另行確認。</p></div></div></div></>:<div className="panel welcome"><div className="welcome-icon"><Wallet size={32}/></div><div className="eyebrow">準備好你的成本資料</div><h2>從一份資料開始，<br/>建立你的車型成本庫。</h2><p>空車、套裝、配車額度與庫存保留各自的來源。確認條件後，再輸入成交價、車貸與舊車折抵，兩種結果一起看。</p><div className="flow"><span>01 上傳資料</span><span>02 核對條件</span><span>03 查詢試算</span></div><button className="primary" onClick={()=>setTab('intake')}><Upload size={18}/>上傳第一份資料</button><small>未提供資料前，不預填市場車價或補助金額。</small></div>}</section></div></TabsContent>
 <TabsContent value="packages"><PackagePicker packages={packages}/></TabsContent>
 <TabsContent value="intake"><div className="intake-grid"><section><div className="panel upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void intake(e.dataTransfer.files);}}><span className="upload-icon"><Upload size={28}/></span><h2>把資料放進來，逐筆核對</h2><p>書面拍照、成本表、庫存郵件都可以上傳。</p><button className="primary" disabled={busy} onClick={()=>uploadInput.current?.click()}>{busy?<LoaderCircle className="spin" size={18}/>:<Plus size={18}/>}選擇檔案／照片</button><p className="supported">PDF · JPG／PNG／WEBP · Excel／CSV · DOCX · TXT／EML<br/>單檔 15 MB；PDF 最多判讀 30 頁</p>{busy&&<div className="progress-message" role="status">{progress||'正在建立草稿…'}</div>}<button className="text-button" onClick={downloadTemplate}><Download size={15}/>下載 Excel／CSV 匯入欄位範本</button></div>
 <div className="panel text-panel"><div className="panel-title"><h2><FileText size={18}/>貼上文字／郵件內容</h2>{activeSource&&<SourceLink id={activeSource}>查看原始檔案</SourceLink>}</div><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'車型：COROLLA CROSS\n等級：請填寫實際版本\n空車成本：請填寫實際金額\n配車額度：請填寫數量\n庫存：請填寫數量\n\n不同車型請以空白行分隔。'}/><div className="text-footer"><span>文字判讀以欄位名稱與數字為依據。</span><button className="secondary" disabled={busy||!raw.trim()} onClick={()=>void textIntake()}>判讀並保存草稿</button></div></div></section>
 <section className="panel review-panel"><div className="panel-title"><h2>待確認清單 <span className="count">{drafts.length}</span></h2><button className="icon-button" aria-label="重新載入草稿" onClick={()=>void load()}><RefreshCw size={17}/></button></div>{drafts.some(x=>x.kind==='accessory-package')&&<button className="secondary" disabled={saving} onClick={()=>void confirmPackages()}>確認匯入全部配件套裝（{drafts.filter(x=>x.kind==='accessory-package').length} 筆）</button>}<div className="notice"><CircleHelp size={18}/>文字辨識可能誤讀數字；未確認的草稿不會進入成本試算。</div>{drafts.length?drafts.map(x=><article className="draft-card" key={x.id}><div><span className="badge amber">待核對</span><h3>{x.model||'未辨識車型'}</h3><p>{x.packageInfo?.code&&`${x.packageInfo.code} · `}{x.trim||'請補填等級'} · {x.year||'請補填年式'}</p></div>{x.packageInfo&&<p>配件套裝 · {x.packageInfo.items.length} 項 · 業代價合計 ${fmt(x.packageInfo.dealerTotal)} · 套裝價 ${fmt(x.packageInfo.bundlePrice)}</p>}<div className="draft-values"><span>空車 <b>{fmt(x.bare)}</b></span><span>套裝 <b>{fmt(x.package)}</b></span><span>庫存 <b>{fmt(x.stock)}</b></span></div><p className="source-name">{sourceName(x.sourceId)}</p><button className="secondary" onClick={()=>setEditor({...x})}>核對／確認資料</button></article>):<div className="empty"><Check size={34}/><h3>目前沒有待確認資料</h3><p>上傳後會列出辨識草稿，缺漏欄位可手動補填。</p></div>}</section></div></TabsContent>
 <TabsContent value="sources"><section className="panel mail-panel"><div className="mail-logo"><Mail size={24}/></div><div><h2>Gmail 配車郵件</h2><p>尚未連接 · 目前可上傳 .eml 郵件檔或貼上郵件內容。</p><small>直接同步 Gmail 仍需完成信箱授權與網站串接設定。目前不會自動讀取信箱。</small></div><button className="secondary" onClick={()=>{setTab('intake');uploadInput.current?.click();}}>匯入郵件檔</button></section><section className="panel source-panel"><div className="panel-title"><h2>來源資料</h2><span>{sources.length} 份檔案</span></div>{sources.length?<Table><TableHeader><TableRow><TableHead>檔案名稱</TableHead><TableHead>上傳時間</TableHead><TableHead>對應條件</TableHead><TableHead>原始檔</TableHead></TableRow></TableHeader><TableBody>{sources.map(s=><TableRow key={s.id}><TableCell><FileText className="inline-icon"/>{s.name}</TableCell><TableCell>{new Date(s.created_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}</TableCell><TableCell>{vehicles.filter(x=>x.sourceId===s.id).length} 筆</TableCell><TableCell><SourceLink className="download-link" id={s.id}><Download size={15}/>下載</SourceLink>{/\.(xlsx|xls|csv)$/i.test(s.name)&&<button className="secondary" disabled={busy} onClick={()=>void reparseSource(s)}>重新解析 Excel</button>}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><Layers size={36}/><h3>原始資料會保留在這裡</h3><p>核對成本時，可以隨時下載原檔查看。</p></div>}</section></TabsContent></Tabs>
 <footer>JC AUTO COST <span>成本依你提供的資料建立 · 各方案與日期分開保存</span></footer>
 <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!saving)setEditor(null);}}><DialogContent className="editor-dialog"><DialogTitle>{editor?.status==='confirmed'?'編輯車型條件':'核對車型條件'}</DialogTitle><DialogDescription>{editor?.kind?'請核對套裝代碼、適用版本、配件明細與各種價格；本筆為配件套裝。':'請對照原檔確認金額。空白代表未知，0 代表確認沒有；套裝填包含空車的總成本。'}</DialogDescription>{editor&&<><div className="editor-source">來源：{sourceName(editor.sourceId)}{editor.sourceId&&<SourceLink id={editor.sourceId}>下載原檔</SourceLink>}</div>{editor.packageInfo&&<><p>配件套裝 {editor.packageInfo.code} · {editor.packageInfo.sheet}</p><p>配件明細：{editor.packageInfo.items.map(i=>`${i.name}（${fmt(i.price)}）`).join('、')}</p><div className="editor-fields">{(['dealerTotal','bundlePrice','quote'] as const).map((k,i)=><label key={k}>{['配件業代價合計','表列套裝價','統一報價'][i]}<input type="number" min="0" value={editor.packageInfo![k]??''} onChange={e=>setEditor({...editor,packageInfo:{...editor.packageInfo!,[k]:e.target.value===''?null:Number(e.target.value)}})}/></label>)}</div></>}<div className="editor-fields">{Object.entries(labels).filter(([k])=>k!=='note'&&(!editor.kind||['model','trim','year','validFrom','validTo'].includes(k))).map(([k,label])=><label key={k}>{label}<input type={numericFields.includes(k as any)?'number':k.startsWith('valid')?'date':'text'} min="0" step="1" inputMode={numericFields.includes(k as any)?'numeric':undefined} value={(editor as any)[k]??''} placeholder={numericFields.includes(k as any)?'未知請留空':''} onChange={e=>setEditor({...editor,[k]:numericFields.includes(k as any)?(e.target.value===''?null:Number(e.target.value)):e.target.value})}/></label>)}</div>{!editor.kind&&<div className="editor-fields">{(['referencePrice','rebatePercent','commissionPercent'] as const).map((k,i)=><label key={k}>{['車價基準／牌價','原廠額外獎金（%）','佣金（貸款本金 %）'][i]}<NumericInput value={editor[k]??0} decimal={k!=='referencePrice'} max={k==='referencePrice'?1e9:100} onValue={n=>setEditor({...editor,[k]:n})}/></label>)}</div>}<label className="note-label">條件／備註<textarea value={editor.note} onChange={e=>setEditor({...editor,note:e.target.value})}/></label><div className="editor-actions"><button className="secondary" disabled={saving} onClick={()=>void save(editor,'draft')}>保存草稿</button><button className="primary" disabled={saving||!editor.model.trim()} onClick={()=>void save(editor,'confirmed')}><Check size={17}/>{saving?'儲存中…':'確認並加入查詢'}</button></div></>}</DialogContent></Dialog>
 </main>;
}
